/**
 * Stable codes for every operational failure in the app.
 * Logs and toasts branch on these. The message text can change.
 */
const ErrorCode = Object.freeze({
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INVALID_PRODUCT_PAGE: 'INVALID_PRODUCT_PAGE',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NOT_EMPTY: 'CATEGORY_NOT_EMPTY',
  ORDER_LINES_EMPTY: 'ORDER_LINES_EMPTY',
  ORDER_QUANTITY_INVALID: 'ORDER_QUANTITY_INVALID',
  PRINTER_BUSY: 'PRINTER_BUSY',
  PRINT_FAILED: 'PRINT_FAILED',
  IMAGE_FILE_INVALID: 'IMAGE_FILE_INVALID',
  IMAGE_FILE_TOO_LARGE: 'IMAGE_FILE_TOO_LARGE',
  IMAGE_TYPE_UNSUPPORTED: 'IMAGE_TYPE_UNSUPPORTED',
  IMAGE_STORE_MISCONFIGURED: 'IMAGE_STORE_MISCONFIGURED',
  DATE_UNRECOGNISED: 'DATE_UNRECOGNISED',
  SALES_WINDOW_UNKNOWN: 'SALES_WINDOW_UNKNOWN',
  USE_CASE_UNKNOWN: 'USE_CASE_UNKNOWN',
  UNEXPECTED: 'UNEXPECTED'
});

export default ErrorCode;
